package com.edcarlos.model.bean;
// Generated May 9, 2017 9:05:58 AM by Hibernate Tools 4.3.1

/**
 * Estudante generated by hbm2java
 */
public class Estudante implements java.io.Serializable {

    private Integer estcodigo;
    private String estnome;
    private String estsobrenome;
    private String estmassa;
    private String estaltura;

    public Estudante() {
    }

    public Estudante(String estnome, String estsobrenome, String estmassa, String estaltura) {
        this.estnome = estnome;
        this.estsobrenome = estsobrenome;
        this.estmassa = estmassa;
        this.estaltura = estaltura;
    }

    public Integer getEstcodigo() {
        return this.estcodigo;
    }

    public void setEstcodigo(Integer estcodigo) {
        this.estcodigo = estcodigo;
    }

    public String getEstnome() {
        return this.estnome;
    }

    public void setEstnome(String estnome) {
        this.estnome = estnome;
    }

    public String getEstsobrenome() {
        return this.estsobrenome;
    }

    public void setEstsobrenome(String estsobrenome) {
        this.estsobrenome = estsobrenome;
    }

    public String getEstmassa() {
        return this.estmassa;
    }

    public void setEstmassa(String estmassa) {
        this.estmassa = estmassa;
    }

    public String getEstaltura() {
        return this.estaltura;
    }

    public void setEstaltura(String estaltura) {
        this.estaltura = estaltura;
    }

}
